### ISSUE TITLE
Is getActiveOverlayLayers() asynchronous?

### ISSUE THREAD

**Issue by petemills** [vogdb/Leaflet.ActiveLayers#3]
I'm attempting something quite simple using the following code:

currentActiveLayers = control.getActiveOverlayLayers();

currentLayerList = [];
for (var layer in currentActiveLayers) {
	if (currentActiveLayers.hasOwnProperty(layer)) {
		currentLayerList.push(currentActiveLayers[layer]);
	}
}

This code is within an 'onadd' event for the map object. However, when logging the 'currentLayerList', it will always show the state of the list on the previous event. E.g if the map starts with 2 active layers, when turning a new one on using the control, the list will show two layers, when adding a second (4 total active layers now) it will show 3. I guess this is because it is continuing on with the creation of 'currentLayerList' before 'getActiveOverlayLayers()' has finished executing, and so uses the previous 'currentActiveLayers' object to build the list (currentActiveLayers is global). Is this true or is getActiveOverlayLayers synchronous and the problem is elsewhere?

Thanks,

**Comment by quique0194** [comment]
I'm having a very similar problem:
I'm using a map with several overlay layers and saving the selected ones in the url. I have something like this:

    map.on('overlayadd', function () {
        console.log(control.getActiveOverlayLayers());
    });

The problem is that when you see the output of console.log, it's always on the previous state. I think it may be because the variable _activeOverlayLayers is being updated after the event's call. By the moment, my workaround is as follows:

    map.on('overlayadd', function () {
        setTimeout(function () {
            console.log(control.getActiveOverlayLayers());
        }, 1);
    });

**Comment by vogdb** [comment]
@petemills @quique0194 please verify.

**Comment by quique0194** [comment]
It works! Thanks
